parameters:
    app.path.upload_home: /upload/home
    app.path.upload_annonce: /upload/annonce
    app.path.upload_subscription: /upload/subscription

vich_uploader:
    db_driver: orm
    mappings:
        home_upload:
            uri_prefix: '%app.path.upload_home%'
            upload_destination: '%kernel.project_dir%/public/upload/home'
            inject_on_load:     true
            # Les propriétés delete_on_update et delete_on_remove prennent en charge la suppression de l'image
            # dans le cas d'un changement d'image à l'update l'ancienne image est supprimée.
            delete_on_update:   true
            delete_on_remove:   true 
            # Vichuploader prend en charge le renommage automatique avec namer
            namer: vich_uploader.namer_origname

        annonce_upload:
            uri_prefix: '%app.path.upload_annonce%'
            upload_destination: '%kernel.project_dir%/public/upload/annonce'
            inject_on_load:     true
            # Les propriétés delete_on_update et delete_on_remove prennent en charge la suppression de l'image
            # dans le cas d'un changement d'image à l'update l'ancienne image est supprimée.
            delete_on_update:   true
            delete_on_remove:   true 
            # Vichuploader prend en charge le renommage automatique avec namer
            namer: vich_uploader.namer_origname

        subscription_upload:
            uri_prefix: '%app.path.upload_subscription%'
            upload_destination: '%kernel.project_dir%/public/upload/subscription'
            inject_on_load:     true
            # Les propriétés delete_on_update et delete_on_remove prennent en charge la suppression de l'image
            # dans le cas d'un changement d'image à l'update l'ancienne image est supprimée.
            delete_on_update:   true
            delete_on_remove:   true 
            # Vichuploader prend en charge le renommage automatique avec namer
            namer: vich_uploader.namer_origname
